

                            //   USING THEN, CATCH   //

import axios from 'axios';

const baseUrl = process.env.REACT_APP_BASE_URL
console.log(baseUrl);
export default function HttpRequest({method, url, data}) {
  let token = localStorage.getItem("Auth")
    return axios({
        method: method,
        url: url,
        data: data,
        headers: {
          Authorization: `Bearer ${token}`,
        },
      })
      .then(response => {
        // Handle successful response here
        return response.data;
      })
      .catch(error => {
        // Handle error here
        throw new Error(`API call failed: ${error.message}`);
      });
}

example:

    const fetchData=()=>{
    const method = "Post";
    const url = " http://localhost:4000/update";
    const data = {
        "email": email,
        "password": password
    }

    const response = HttpRequest({ method, url, data });
    response
        .then((res) => {
            console.log(res);
        }).catch((err) => {
            console.log(err);
        })
    }
    

                            //   USING TRY CATCH  //

import axios from 'axios';

const baseUrl = process.env.REACT_APP_BASE_URL;
const HttpRequest = async ({ method, url, data }) => {
  try {
    const token = localStorage.getItem('Auth');
    const response = await axios({
      method: method,
      url: `${url}`, // Assuming you want to use the base URL
      data: data,
      headers: {
        Authorization: `Bearer ${token}`,
      },
    });

    // Handle successful response here
    return response.data;
  } catch (error) {
    // Handle error here
    throw new Error(`API call failed: ${error.message}`);
  }
};

export default HttpRequest;



example:

   const fetchData = async () => {
        const method = "POST";
        const url = "http://localhost:4000/update";
        const request = {
            "email": email,
            "password": password
        }
        try {
            const data = await HttpRequest({ method, url, request });
            console.log('Data:', data);
        } catch (error) {
            console.error('Error:', error.message);
        }
    }